# Settings.yml
---
conf.py:
  project: TYPO3 Security Guide
  copyright: 2011-2014
  version: 1.0.5
  release: 1.0.5
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Guide-Security
    github_branch: latest
...
