# Settings.yml
---
conf.py:
  project: TYPO3 Security Guide
  copyright: 2011-2014
  version: 1.0.6
  release: 1.0.6
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Guide-Security
    github_branch: latest
  latex_documents:
  - - Index
    - t3security.tex
    - TYPO3 Security Guide
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
