# Settings.yml
---
conf.py:
  project: File Abstraction Layer
  copyright: 2012-2014
  version: 6.2
  release: 6.2
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-FileAbstractionLayer
    github_branch: latest
...
