# Settings.yml
---
conf.py:
  project: TypoScript Syntax and In-depth Study
  copyright: 2000-2014
  version: 6.2
  release: 6.2
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-TyposcriptSyntax
    github_branch: latest
  latex_documents:
  - - Index
    - t3tssyntax.tex
    - TypoScript Syntax and In-depth Study
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
