# Settings.yml
---
conf.py:
  project: File Abstraction Layer
  copyright: 2012-2015
  version: 6.2
  release: 6.2
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-FileAbstractionLayer
    github_branch: latest
  latex_documents:
  - - Index
    - t3fal.tex
    - File Abstraction Layer
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
