# Settings.yml
---
conf.py:
  project: TYPO3 CMS Coding Guidelines
  copyright: 2000-2014
  version: 6.2
  release: 6.2
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-CodingGuidelines
    github_branch: latest
...
